/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.tablefork.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TableForkUiModule extends AbstractTableForkUiModule {

	public TableForkUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
