/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.tablefork.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTableForkValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.example.tablefork.tableFork.TableForkPackage.eINSTANCE);
		return result;
	}
}
