/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.tablefork;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TableForkStandaloneSetup extends TableForkStandaloneSetupGenerated {

	public static void doSetup() {
		new TableForkStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
