/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.tablefork.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.tablefork.ui.internal.TableforkActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TableForkExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TableforkActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TableforkActivator activator = TableforkActivator.getInstance();
		return activator != null ? activator.getInjector(TableforkActivator.ORG_XTEXT_EXAMPLE_TABLEFORK_TABLEFORK) : null;
	}

}
