/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.tablefork.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.tablefork.ui.internal.TableforkActivator;

public class TableForkUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TableforkActivator.getInstance().getInjector("org.xtext.example.tablefork.TableFork");
	}

}
