/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.tablefork.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TableForkAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/tablefork/parser/antlr/internal/InternalTableFork.tokens");
	}
}
