/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.tablefork.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.tablefork.parser.antlr.internal.InternalTableForkParser;
import org.xtext.example.tablefork.services.TableForkGrammarAccess;

public class TableForkParser extends AbstractAntlrParser {

	@Inject
	private TableForkGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTableForkParser createParser(XtextTokenStream stream) {
		return new InternalTableForkParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public TableForkGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TableForkGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
